# Generated by Django 5.0.2 on 2024-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indirizzo')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('license_code', models.CharField(max_length=100, unique=True, verbose_name='Codice Licenza')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('start_date', models.DateField(verbose_name='Data Inizio')),
                ('end_date', models.DateField(verbose_name='Data Scadenza')),
            ],
            options={
                'verbose_name': 'Gestione Licenza',
                'verbose_name_plural': 'Gestione Licenze',
            },
        ),
    ]
