# Generated by Django 5.0.2 on 2024-02-27 15:14

import django.db.models.deletion
import prototyping.models.chassis_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='data_creazione')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='data_ultima_modifica')),
                ('file', models.FileField(upload_to=prototyping.models.chassis_models.chassis_directory_path, verbose_name='file')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.license', verbose_name='id_licenza')),
            ],
            options={
                'verbose_name': 'chassis',
                'verbose_name_plural': 'chassis',
            },
        ),
    ]
