# Generated by Django 5.0.2 on 2024-02-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0003_aptica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('component_count', models.IntegerField(verbose_name='numero di componenti')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.chassis', verbose_name='ID Chassis')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementi',
            },
        ),
    ]
