# Generated by Django 5.0.2 on 2024-02-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0004_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aptica',
            options={'verbose_name': 'Aptic', 'verbose_name_plural': 'Aptic'},
        ),
    ]
