# Generated by Django 5.0.2 on 2024-02-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0005_alter_aptica_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.IntegerField(verbose_name='id_versione')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('position_x', models.FloatField(verbose_name='posizione x')),
                ('limit_position_x', models.FloatField(verbose_name='limite posizione x')),
                ('position_y', models.FloatField(verbose_name='posizione y')),
                ('limit_position_y', models.FloatField(verbose_name='limite posizione y')),
                ('position_z', models.FloatField(verbose_name='posizione z')),
                ('limit_position_z', models.FloatField(verbose_name='limite posizione z')),
                ('rotation_x', models.FloatField(verbose_name='rotazione x')),
                ('limit_rotation_x', models.FloatField(verbose_name='limite rotazione x')),
                ('rotation_y', models.FloatField(verbose_name='rotazione y')),
                ('limit_rotation_y', models.FloatField(verbose_name='limite rotazione y')),
                ('rotation_z', models.FloatField(verbose_name='rotazione z')),
                ('limit_rotation_z', models.FloatField(verbose_name='limite rotazione z')),
                ('rotation_w', models.FloatField(verbose_name='rotazione w')),
                ('limit_rotation_w', models.FloatField(verbose_name='limite rotazione w')),
                ('area_radius', models.FloatField(verbose_name='area/raggio')),
                ('haptic_stiffness', models.FloatField(verbose_name='aptic stifness')),
                ('haptic_temperature', models.FloatField(verbose_name='aptic temperature')),
                ('haptic_texture', models.IntegerField(verbose_name='aptic texture')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componenti',
            },
        ),
    ]
