# Generated by Django 5.0.2 on 2024-02-28 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0008_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('message', models.TextField(verbose_name='messaggio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.client', verbose_name='cliente')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.project', verbose_name='progetto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'Messaggio',
                'verbose_name_plural': 'Messaggi',
            },
        ),
    ]
