# Generated by Django 5.0.2 on 2024-02-28 14:07

import django.db.models.deletion
import django.utils.timezone
import prototyping.models.component_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data di creazione'),
        ),
        migrations.AddField(
            model_name='component',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototyping.element', verbose_name='elemento'),
        ),
        migrations.AddField(
            model_name='component',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=prototyping.models.component_model.component_directory_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='component',
            name='limit_position_x',
            field=models.FloatField(blank=True, null=True, verbose_name='limite posizione x'),
        ),
        migrations.AlterField(
            model_name='component',
            name='limit_position_y',
            field=models.FloatField(blank=True, null=True, verbose_name='limite posizione y'),
        ),
        migrations.AlterField(
            model_name='component',
            name='limit_position_z',
            field=models.FloatField(blank=True, null=True, verbose_name='limite posizione z'),
        ),
        migrations.AlterField(
            model_name='component',
            name='limit_rotation_w',
            field=models.FloatField(blank=True, null=True, verbose_name='limite rotazione w'),
        ),
        migrations.AlterField(
            model_name='component',
            name='limit_rotation_x',
            field=models.FloatField(blank=True, null=True, verbose_name='limite rotazione x'),
        ),
        migrations.AlterField(
            model_name='component',
            name='limit_rotation_y',
            field=models.FloatField(blank=True, null=True, verbose_name='limite rotazione y'),
        ),
        migrations.AlterField(
            model_name='component',
            name='limit_rotation_z',
            field=models.FloatField(blank=True, null=True, verbose_name='limite rotazione z'),
        ),
    ]
