# Generated by Django 5.0.2 on 2024-02-28 15:06

import django.db.models.deletion
import prototyping.models.release_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0010_component_created_at_component_element_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('file', models.FileField(upload_to=prototyping.models.release_models.release_directory_path, verbose_name='file')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='data creazione')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.client', verbose_name='id_cliente')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.project', verbose_name='id_progetto')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
    ]
