# Generated by Django 5.0.2 on 2024-02-28 16:54

import django.db.models.deletion
import prototyping.models.component_release_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0011_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=prototyping.models.component_release_models.component_release_file_path, verbose_name='File')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.chassis', verbose_name='Chassis')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.component', verbose_name='Component')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.element', verbose_name='Element')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.release', verbose_name='Release')),
            ],
            options={
                'verbose_name': 'Component Release',
                'verbose_name_plural': 'Component Releases',
            },
        ),
    ]
