# Generated by Django 5.0.2 on 2024-03-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0013_remove_element_component_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='component',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='component',
            name='position_z',
        ),
        migrations.RemoveField(
            model_name='component',
            name='rotation_w',
        ),
        migrations.RemoveField(
            model_name='component',
            name='rotation_x',
        ),
        migrations.RemoveField(
            model_name='component',
            name='rotation_y',
        ),
        migrations.RemoveField(
            model_name='component',
            name='rotation_z',
        ),
    ]
