# Generated by Django 5.0.2 on 2024-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0014_remove_component_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='numero componente'),
        ),
    ]
