# Generated by Django 5.0.2 on 2024-03-19 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0016_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_release_date',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data fine'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data inizio'),
        ),
    ]
