# Generated by Django 5.0.2 on 2024-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='letto'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
